### ISSUE TITLE
cannot convert an array value in an array value. ERROR

### ISSUE THREAD

**Issue by momoDragon** [jloosli/node-firestore-import-export#45]
### Expected behavior
this is the data i am adding to a field:
[ [ '-LXRXPFgA6sC9Mg0GQMt', 2, 'Sushi premium' ], [ '-LXRSAp3jpB8EUbZU-0c', 1, 'Caramel Glazed Donuts' ] ]

### Actual behavior
3 INVALID_ARGUMENT: Cannot convert an array value in an array value.
at Object.exports.createStatusError (/user_code/node_modules/firebase-admin/node_modules/grpc/src/common.js:91:15)
at Object.onReceiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:1204:28)
at InterceptingListener._callNext (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:568:42)
at InterceptingListener.onReceiveStatus (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:618:8)
at callback (/user_code/node_modules/firebase-admin/node_modules/grpc/src/client_interceptors.js:845:24)

### Steps to reproduce the behavior
add this to a field of a doc with cloud function https  [ [ '-LXRXPFgA6sC9Mg0GQMt', 2, 'Sushi premium' ], [ '-LXRSAp3jpB8EUbZU-0c', 1, 'Caramel Glazed Donuts' ] ]

**Comment by Mikkelet** [comment]
How di you fix it?

**Comment by momoDragon** [comment]
@Mikkelet  i didnt. i had to restructure [{'key: 'value'},{},{}]

**Comment by Viamo** [comment]
In my project I need to save the data I receive in the database, but the data can come in any format and I can't influence its format. After learning about this error I can't use Firebase DB anymore because one day I can get an array in the array and the system will crash. Forced to give up on Firebase which is very frustrating for me.
