### ISSUE TITLE
 UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped

### ISSUE THREAD

**Issue by ziarv** [jloosli/node-firestore-import-export#683]
node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 9)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 10)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 11)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 13)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 14)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 15)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 16)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 17)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31
(node:25352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 18)
(node:25352) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connection dropped
    at Object.callErrorFromStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call.js:30:26)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client.js:328:49)
    at Object.onReceiveStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)
    at Http2CallStream.outputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)
    at Http2CallStream.maybeOutputStatus (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)
    at Http2CallStream.endCall (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)
    at Http2CallStream.disconnectListener (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/call-stream.js:103:18)
    at TLSSocket.<anonymous> (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@grpc/grpc-js/build/src/subchannel.js:344:25)
    at Object.onceWrapper (events.js:284:20)
    at TLSSocket.emit (events.js:201:15)
Caused by: Error
    at Firestore.getAll (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/index.js:683:23)
    at DocumentReference.get (/usr/local/lib/node_modules/node-firestore-import-export/node_modules/@google-cloud/firestore/build/src/reference.js:199:32)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:56:43
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:4:12)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:56
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/node-firestore-import-export/dist/lib/export.js:55:31

**Comment by GemsGame** [comment]
it's package have memory leak, use https://www.npmjs.com/package/@sgg10/firestore-backup
works well
