### ISSUE TITLE
Import fails

### ISSUE THREAD

**Issue by hhimanshu** [jloosli/node-firestore-import-export#9]
### Expected behavior
The import should have run  

### Actual behavior    
```
➜  node-firestore-import-export git:(master) node ./dist/bin/firestore-import.js --accountCredentials ~/Downloads/staging-cd6a5-firebase-adminsdk-771d4477a1.json --backupFile mb_staging.json
/Users/harit/bl/sources/webs/q2/node-firestore-import-export/dist/bin/firestore-import.js:55
    const [data, pathReference] = res;
          ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
➜  node-firestore-import-export git:(master)


### Steps to reproduce the behavior  
- Checkout the codebase  
- Run the following commands  

```bash
npm install && npm run build
```  
- export your data using `README.md`. This command works fine.  
- Import your data using `README.md` command. This fails.  
```bash
➜  node-firestore-import-export git:(master) node ./dist/bin/firestore-import.js --accountCredentials ~/Downloads/staging-cd6a5-firebase-adminsdk-zk1to-771d4477a1.json --backupFile mb_staging.json
/Users/harit/bl/sources/webs/q2/node-firestore-import-export/dist/bin/firestore-import.js:55
    const [data, pathReference] = res;
          ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
➜  node-firestore-import-export git:(master)

```

**Comment by jloosli** [comment]
What versions of Node/NPM are you running?

**Comment by jloosli** [comment]
I'm guessing it's a [destructuring](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) issue...if you're running node pre v6, that could cause problems. 

Can you try changing the `target` to `ES5` or `ES3` in the tsconfig and then running `npm run build` again?

```
"target": "ES5"
```

**Comment by hhimanshu** [comment]
Oh yes, Thanks a lot, @jloosli , that was the issue. I verified it by updating the node version. Additionally, I have seen a issue with the export-import. This is related to the type of the data. For example, the data type for a field was `Timestamp`, but when downloaded, it because `String` and during `import`, it was uploaded as `String`. This breaks the business logic to fetch the data.
